### ISSUE TITLE
Readme missing section

### ISSUE THREAD

**Issue by xenoryt** [DavidGamba/go-getoptions#11]
README file leaves me hanging: https://github.com/DavidGamba/go-getoptions/blame/master/README.adoc#L357
Using blame view because GitHub doesn't support show correct line when trying to view file normally https://github.com/DavidGamba/go-getoptions/blob/master/README.adoc#L357

**Comment by DavidGamba** [comment]
I can see how you would feel that. What it needs is a link to the next set of features where I introduce the additional types and the extra features. There is no missing section, just bad writting ;-)

**Comment by xenoryt** [comment]
oooh I see it was continuation from https://github.com/DavidGamba/go-getoptions/blame/master/README.adoc#L325. I understand now :+1:
