### ISSUE TITLE
help aliases ignored when Required() option is set

### ISSUE THREAD

**Issue by werelord** [DavidGamba/go-getoptions#12]
I'm getting some weird help functionality when Required() is included on an option.  Here's the playground link demonstrating this:

https://go.dev/play/p/6Wma6dc3HbA

Calling with "--help", or "help <command>" calls, getoptions.Parse() fails due to the required option missing... But only in those cases; just using "help" alone doesn't fail the parse.

Thoughts?

**Comment by DavidGamba** [comment]
Thanks for giving me a reproduction method, that is great.
Your second test needs to be changed:

```diff
- test("help foo")
+ test("help", "foo")
```

The third test is a valid issue. I am basically checking for required options before checking if the help option was passed.

**Comment by davidgamba-au** [comment]
I think that https://github.com/DavidGamba/go-getoptions/tree/issue-12-check-required-before-help fixes your problem.
Please Take a look. I'll cut a new release with that change in the next few days.

**Comment by DavidGamba** [comment]
I think that https://github.com/DavidGamba/go-getoptions/tree/issue-12-check-required-before-help fixes your problem.
Please Take a look. I'll cut a new release with that change in the next few days.

**Comment by werelord** [comment]
Yeah, that bug in the sandbox; side effect of modifying the sandbox instead of actually debugging in my environment. Good catch..

Ran thru the changes in my project, it appears to be working now; no issues found.. Perfect, thanks for the quick turnaround!!

**Comment by DavidGamba** [comment]
Awesome, I'll merge and bump today when I have a chance.

**Comment by DavidGamba** [comment]
You can update to https://github.com/DavidGamba/go-getoptions/releases/tag/v0.26.0
Thanks again for the report!
