### ISSUE TITLE
[question] How to do positional arguments? 

### ISSUE THREAD

**Issue by a4z** [DavidGamba/go-getoptions#7]
First of all, thanks for this library, I am super new to go, but your docs and example make it pretty easy to get started creating some app that takes commands and arguments, and it's fun!

One issue though, I could not figure out how to get something like pythons argparse positional argument
https://docs.python.org/3/howto/argparse.html#introducing-positional-arguments

Specifying the name(s) of argument values that are not passed via a flag, but at the end of a command.

I could of course use the remaining args from opt.Parse, but then there is no help entry...
Did I miss something in the docs, or is it not mentioned?

**Comment by DavidGamba** [comment]
It is not called out in the README, the godoc does have information about it, however, there is no example:
https://pkg.go.dev/github.com/DavidGamba/go-getoptions#GetOpt.HelpSynopsisArgs

If you run the [myscript](https://github.com/DavidGamba/go-getoptions/tree/master/examples/myscript) example, you get the following output as part of the help:

```
SYNOPSIS:
    myscript --greet <int> [--debug] [--help|-h|-?] [--list <key=value>...]...
             [<args>]
```

If you add the HelpSynopsisArg override:

```diff --git main.go main.go
index be9caef..a5d1f5f 100644
--- main.go
+++ main.go
@@ -16,6 +16,7 @@ func main() {
    var greetCount int
    var list map[string]string
    opt := getoptions.New()
+   opt.HelpSynopsisArgs("<echo_string>")
    opt.Bool("help", false, opt.Alias("h", "?"))
    opt.BoolVar(&debug, "debug", false, opt.GetEnv("DEBUG"))
    opt.IntVar(&greetCount, "greet", 0,
```

You get:

```SYNOPSIS:
    myscript --greet <int> [--debug] [--help|-h|-?] [--list <key=value>...]...
             <echo_string>
```

As far as documenting what your argument is, vs what your options expect, I would probably do it in the NAME section:

```diff
index be9caef..04c2764 100644
--- main.go
+++ main.go
@@ -16,6 +16,8 @@ func main() {
    var greetCount int
    var list map[string]string
    opt := getoptions.New()
+   opt.Self("", "echoes the given string")
+   opt.HelpSynopsisArgs("<echo_string>")
    opt.Bool("help", false, opt.Alias("h", "?"))
    opt.BoolVar(&debug, "debug", false, opt.GetEnv("DEBUG"))
    opt.IntVar(&greetCount, "greet", 0,
```


```
NAME:
    myscript - echoes the given string

SYNOPSIS:
    myscript --greet <int> [--debug] [--help|-h|-?] [--list <key=value>...]...
             <echo_string>
```

Each subcommand has a `Self` method, so you can edit the help of each subcommand as well.

**Comment by a4z** [comment]
Awesome, that works great. Thanks a lot David! 

This library is great! 
Not just because it allows me to keep a known command line interface with `-s/ --some-value` and even `-vvv` for verbose level 3 and subcommands and everything, without switching to a new way of  `-onlyso` , but also for learning about go!
It is really nice to read through your code, thank you for sharing your work!
