### ISSUE TITLE
Question: Possible to add sub commands to sub commands?

### ISSUE THREAD

**Issue by a4z** [DavidGamba/go-getoptions#8]
Is it possible to add NewCommand to a NewCommand 

to create a command line interface like that
``` 
mytool make new -h
mytool make init -s=whatever

mytool do check -h
mytool do run --program=whatever
```
I hope that explains what I would like to achive

**Comment by DavidGamba** [comment]
yes, that is part of the design, I took quite a while to respond with that yes so hopefully you already gave it a try and it worked for you.

I have done tools a couple levels deep. Also, keep in mind that there is nothing making it so NewCommand can't be run in a loop after reading a list of programs from a file or even expanding a dir structure first.

So your tool could have a list of programs and those programs could be a command itself:

```
mytool do run program whatever --opts...
```

I like that pattern because currently commands are autocompleted and option values are not (though I am working on that).

**Comment by a4z** [comment]
Haven't given up :-) 
But I could not find an example for that, and since I have no stress I played with other things, still new to go so there is a lot to do.
 
I think I can imaging how it might work, but having some example would be nice for newbies like me

Maybe something like that? 
```
func AddCommand1(parent *getoptions.GetOpt) *getoptions.GetOpt {
	opt := parent.NewCommand("command1", "This is the first command")

	return AddSubCommand(opt)
}

func AddSubCommand(parent *getoptions.GetOpt) *getoptions.GetOpt {
	opt := parent.NewCommand("subcommand", "This is the sub command")
       // set up the rest 
	return opt
}
```

**Comment by DavidGamba** [comment]
This is a snippet of how it looks like from the tests:
https://github.com/DavidGamba/go-getoptions/blob/master/go-getoptions_test.go#L2551-L2558

Will have to update the examples, but I won't get to probably until the weekend.

**Comment by a4z** [comment]
Thanks a lot, this should give me enough to get started using sub commands! 

Therefore I close this issue, but please let you not stop updating the docs once you find some time since this could be really helpful!

**Comment by a4z** [comment]
can't close the issue, since I have one

```
┌───────────────────────────<
│.../work/go/cmdargs on  getopts [!?] via 🐹 v1.17  
└─> go run . command3 subcommand -h
NAME:
    cmdargs command3 subcommand - This is sub command

SYNOPSIS:
    cmdargs command3 subcommand --required <string> [--help|-h|-?] [<args>]

REQUIRED PARAMETERS:
    --required <string>

OPTIONS:
    --help|-h|-?           (default: false)

exit status 1

┌───────────────────────────<
│.../work/go/cmdargs on  getopts [!?] via 🐹 v1.17  
└─> go run . command3 subcommand 
ERROR: Missing required option 'required'!
exit status 1

┌───────────────────────────<
│.../work/go/cmdargs on  getopts [!?] via 🐹 v1.17  
└─> go run . command3 subcommand --required foo
ERROR: Unknown option 'required'
exit status 1

```

so the test works, but you do not test processing given arguments to the subcommand, and that fails in my case

**Comment by a4z** [comment]
I would also like to mention that I think the exit status of a help command should be 0, not 1, since I asked for help and everything worked

**Comment by DavidGamba** [comment]
Very late answer:

Just like at the top level there is an `opt.Dispatch` call that basically dispatches the current request onto the commands, each command of subcommands needs to explicitely dispatch down too:

```
package cmd

import (
	"context"

	"github.com/DavidGamba/dgtools/run"
	"github.com/DavidGamba/go-getoptions"
)

func NewCMD(parent *getoptions.GetOpt) *getoptions.GetOpt {
	opt := parent.NewCommand("cmd", "").SetCommandFn(CMDRun)
	opt.NewCommand("sub-cmd", "").SetCommandFn(SubCMDRun)
	return opt
}

func CMDRun(ctx context.Context, opt *getoptions.GetOpt, args []string) error {
	return opt.Dispatch(ctx, "help", args)
}

func SubCMDRun(ctx context.Context, opt *getoptions.GetOpt, args []string) error {
	err := run.CMD("echo", "hello", "world!").Log().Run()
	if err != nil {
		return err
	}
	return nil
}
```

**Comment by a4z** [comment]
Awesome, this seem to work, thanks!

**Comment by DavidGamba** [comment]
@a4z I am about to finish the newer version of the lib. Expect way simpler workflow in the command and subcommand areas and significantly improved completion support.

**Comment by a4z** [comment]
Looking forward to the new version!
